### ISSUE TITLE
Redirection shaq when no right

### ISSUE THREAD

**Issue by Devauxni** [yoctu/shaq-view#40]
Hello,
WHen the user has no right on an agency / customer / carrier on the shaq, could we have an error message instead of infinite loop please?

**Comment by lvenier** [comment]
fixed on test for now. more testing required.

**Comment by Devauxni** [comment]
Hello,
Should I test in prod ?
In prod I still have the issue.

**Comment by lvenier** [comment]
nope there is test envirronement.

**Comment by Devauxni** [comment]
Ok on test I'm redirecting to :
https://shaq.test.skoreway.com/center.html?usercode=02/display

So no more infinite loop when I do not have the right, however now it seems no possible to access when I've the right
Ex : https://shaq.test.skoreway.com/center.html?usercode=82/display

**Comment by lvenier** [comment]
https://shaq.test.skoreway.com/center.html?usercode=02
https://shaq.test.skoreway.com/display.html?usercode=02&key=NUMEROORDRE

check if it works. I am testing with 
https://shaq.test.skoreway.com/center.html?usercode=82SKOREX&env=.us

**Comment by Devauxni** [comment]
The not authorized work, however I've a grey screen when I've the right, instead to see the SHAQ

**Comment by lvenier** [comment]
can you provide the url ?

**Comment by Devauxni** [comment]
yep :

Login : ftaggart / pwd : test
https://shaq.test.skoreway.com/center.html?usercode=82SKOREWAYHQ

Login : n.henrion@easy4pro.com / pwd : test
https://shaq.test.skoreway.com/center.html?usercode=82 (agency)
https://shaq.test.skoreway.com/center.html?usercode=82SKOREX (carrier)
https://shaq.test.skoreway.com/display.html?usercode=82&key=EP20068HKH (agency+ordre)

**Comment by lvenier** [comment]
Login : ftaggart / pwd : test
https://shaq.test.skoreway.com/center.html?usercode=82SKOREWAYHQ
will not work this is Skoreway front.

n.henrion@easy4pro.com / pwd : test
https://shaq.test.skoreway.com/center.html?usercode=82SKOREX&env=.us
does work.
test.
